test_that("check infrageneric works", {
  expect_equal(infrageneric_level("Astragalus sp."), '0.indet')
  expect_equal(infrageneric_level("Mammillaria sp. f. cristata"), '0.indet')
  expect_equal(infrageneric_level("\xd7 Aridaria sp."), '0.indet')
  expect_equal(infrageneric_level("Fritillaria sp. nov. 'Lemon-green, two-flowered'"), '0.indet')
  expect_equal(infrageneric_level("Fuchsia spec. nov. fuchsia"), '0.indet')

  expect_equal(infrageneric_level("Saxegothaea conspicua"), '1.species')

  expect_equal(infrageneric_level("Rhododendron charitopes subsp. tsangpoense"), '2.subsp')

  expect_equal(infrageneric_level("Rhododendron saluenense var. prostratum"), '3.var')
  expect_equal(infrageneric_level("Schima wallichii subsp. noronhae var. superba"), '3.var')

  expect_equal(infrageneric_level("Aquilegia flabellata f. alba"), '4.f')
  expect_equal(infrageneric_level("Brassica oleracea var. capitata f. rubra"), '4.f')
  expect_equal(infrageneric_level("Polemonium caeruleum subsp. caeruleum f. album"), '4.f')
  expect_equal(infrageneric_level("Aquilegia flabellata subsp. alba var. alba f. alba"), '4.f')

  expect_equal(infrageneric_level("Cordyline fruticosa cv."), '5.cultivar')
  expect_equal(infrageneric_level("Ocimum basilicum 'CV'"), '5.cultivar')
  expect_equal(infrageneric_level("Helleborus orientalis CV"), '5.cultivar')
  expect_equal(infrageneric_level("Iris cv"), '5.cultivar')
  expect_equal(infrageneric_level("Primula whitei 'Arduaire'"), '5.cultivar')
  expect_equal(infrageneric_level("Zephyranthes mesochloa [white]"), '5.cultivar')
  expect_equal(infrageneric_level("Chamaecyparis nootkatensis cv"), '5.cultivar')
  expect_equal(infrageneric_level("Agapanthus [white form]"), '5.cultivar')

  expect_equal(infrageneric_level("Abies hybrid"), '6.hybrid')
  expect_equal(infrageneric_level("Paphiopedilum \xd7 hybrid"), '6.hybrid')
  expect_equal(infrageneric_level("Disa \xd7 Hybrid"), '6.hybrid')
  expect_equal(infrageneric_level("Philadelphus [HYBRID]"), '6.hybrid')
  expect_equal(infrageneric_level("Echinacea tennesseensis ROCKY TOP HYBRIDS"), '6.hybrid')
  expect_equal(infrageneric_level("Nepenthes Ventrata gx"), '6.hybrid')
  expect_equal(infrageneric_level("\xd7 Odontioda Keighleyensis gx"), '6.hybrid')
  expect_equal(infrageneric_level("\xd7 Anoectodes Charlotte's Web gx"), '6.hybrid')
  expect_equal(infrageneric_level("Rhododendron gx Cilpinense"), '6.hybrid')
  expect_equal(infrageneric_level("Phragmipedium Grande gx \xd7 P. caudatum \xd7 P. longifolium"), '6.hybrid')

  expect_equal(infrageneric_level("Tulipa (Darwin Hybrid Group) 'Lalibela'"), '5.cultivar, 6.hybrid')
  expect_equal(infrageneric_level("Rhododendron 'James Russell' [Ciliiicalyx Hybrid]"), '5.cultivar, 6.hybrid')
  expect_equal(infrageneric_level("Hemerocallis (Hybrida Group) 'Margaret Perry'"), '5.cultivar, 6.hybrid')
  expect_equal(infrageneric_level("Rhododendron 'Scarlet Wonder' gx"), '5.cultivar, 6.hybrid')
  expect_equal(infrageneric_level("Pleione gx Shantung 'Ridgeway'"), '5.cultivar, 6.hybrid')

  expect_equal(infrageneric_level("Agastache rugosa f. albiflora 'Honey Bee White'"), "4.f, 5.cultivar")
  expect_equal(infrageneric_level("Erica \xd7 darleyensis f. albiflora 'White Perfection'"), "4.f, 5.cultivar, 6.hybrid")
  expect_equal(infrageneric_level("Iris meda f. protonyma \xd7 barnumiae"), "4.f, 6.hybrid")
  expect_equal(infrageneric_level("Agapanthus inapertus subsp. intermedius 'Wolkberg'"), "2.subsp, 5.cultivar")
  expect_equal(infrageneric_level("Rhododendron kiusianum f. benikomachi hort."), "4.f, 5.cultivar")
  expect_equal(infrageneric_level("Pachyphytum 'Clavata' \xd7 P. bracteosum \xd7 Echeveria sp."), "0.indet, 5.cultivar, 6.hybrid")
})
